
---
- name: Clone Kubespray git project
  git:
    repo: "{{ config.kubernetes.kubespray.url }}"
    version: "{{ config.kubernetes.kubespray.version }}"
    dest: "{{ tkk_cluster_path }}/ansible/kubespray"
    single_branch: yes
    depth: 1
    force: yes