- hosts: haproxy

  gather_facts: false

  tasks:
    - name: Get OS-release
      raw: cat /etc/os-release
      register: os_release
      changed_when: false
      environment: {}

    - name: Install python3
      raw:
        apt-get update -q && \
        DEBIAN_FRONTEND=noninteractive apt-get install -q -y python3
      environment: {}
      when: "'Ubuntu' in os_release.stdout"

    - name: Configure SELinux
      raw:
        yum -q -y install python3-policycoreutils && \
        semanage port -a -t http_port_t -p tcp 6443
      environment: {}
      when: "'CentOS' in os_release.stdout"

    - name: Allow binding non-local IP
      sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: 1
        reload: true
        state: present

    - name: Install Keepalived
      package: name=keepalived state=present

    - name: Configure Keepalived master
      copy:
        src: ../../config/keepalived/keepalived-master.cfg
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart Keepalived
      when: "'lb-0' in inventory_hostname"

    - name: Configure Keepalived backup
      copy:
        src: ../../config/keepalived/keepalived-backup.cfg
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart Keepalived
      when: "'lb-1' in inventory_hostname"

    - name: Start and enable Keepalived
      service: name=keepalived state=started enabled=yes

    - name: Install HAProxy
      package: name=haproxy state=present

    - name: Configure HAProxy
      copy:
        src: ../../config/haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      notify: Restart HAProxy

    - name: Start and enable HAProxy
      service: name=haproxy state=started enabled=yes

  handlers:
    - name: Restart HAProxy
      service: name=haproxy state=restarted

    - name: Restart Keepalived
      service: name=keepalived state=restarted
