- hosts: haproxy
  gather_facts: false

  tasks:
    - name: Get OS release
      raw: cat /etc/os-release
      register: os_release
      changed_when: false
      environment: {}

    - name: Install Python3
      raw:
        apt update -q && \
        DEBIAN_FRONTEND=noninteractive apt install -q -y python3
      environment: {}
      when:
        - "'Ubuntu' in os_release.stdout"
        - "'Debian' in os_release.stdout"

    - name: Configure SELinux on CentOS
      raw:
        yum -q -y install python3-policycoreutils && \
        semanage port -a -t http_port_t -p tcp 6443
      environment: {}
      when:
        - "'CentOS' in os_release.stdout"

    - name: Allow binding non-local IP
      sysctl:
        name: net.ipv4.ip_nonlocal_bind
        state: present
        value: 1
        reload: true

    - name: Install Keepalived
      package:
        name: keepalived
        state: present

    - name: Configure Keepalived
      copy:
        src: ../../config/keepalived/keepalived-{{ inventory_hostname }}.cfg
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart Keepalived

    - name: Start and enable Keepalived
      service:
        name: keepalived
        state: started
        enabled: true

    - name: Install HAProxy
      package:
        name: haproxy
        state: present

    - name: Configure HAProxy
      copy:
        src: ../../config/haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart HAProxy

    - name: Start and enable HAProxy
      service:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

    - name: Restart Keepalived
      service:
        name: keepalived
        state: restarted
