---
default:
  # Default cluster config is used when cluster config does not exist
  # and is not provided (by user).
  cluster_config_path: "{{ cluster_dir }}/resources/default/default-cluster.yaml"
