---
- name: Get OS release
  raw: cat /etc/os-release
  register: os_release
  changed_when: false
  environment: {}

- name: Install Python3
  raw:
    apt update -q && \
    DEBIAN_FRONTEND=noninteractive apt install -q -y python3
  environment: {}
  when:
    - "'Ubuntu' in os_release.stdout"
    - "'Debian' in os_release.stdout"

- name: Configure SELinux on CentOS
  raw:
    yum -q -y install python3-policycoreutils && \
    semanage port -a -t http_port_t -p tcp 6443
  environment: {}
  when:
    - "'CentOS' in os_release.stdout"

- name: Allow binding non-local IP
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    state: present
    value: 1
    reload: true

- name: Setup Keepalived
  include_tasks: configure_keepalived.yaml

- name: Setup Keepalived
  include_tasks: configure_haproxy.yaml