---
- name: Clone Kubespray git project
  git:
    repo: "{{ config.kubernetes.kubespray.url | default( default.kubespray.url ) }}"
    version: "{{ config.kubernetes.kubespray.version }}"
    dest: "{{ kubitect_cluster_path }}/ansible/kubespray"
    single_branch: yes
    depth: 1
    force: yes

- name: Ensure group_vars directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  loop:
    - "{{ config_dir }}/group_vars/all"
    - "{{ config_dir }}/group_vars/k8s_cluster"

- name: Generate Kubespray all.yaml
  template:
    src: all.yaml.j2
    dest: "{{ config_dir }}/group_vars/all/all.yaml"
    # Preserve Kubespray variables intact
    variable_start_string: "<<"
    variable_end_string: ">>"

- name: Generate Kubespray k8s_cluster.yaml
  template:
    src: k8s_cluster.yaml.j2
    dest: "{{ config_dir }}/group_vars/k8s_cluster/k8s_cluster.yaml"
    # Preserve Kubespray variables intact
    variable_start_string: "<<"
    variable_end_string: ">>"
    block_start_string: "<%"
    block_end_string: "%>"

- name: Generate Kubespray etcd.yaml
  template:
    src: etcd.yaml.j2
    dest: "{{ config_dir }}/group_vars/etcd.yaml"
    #dest: "{{ config_dir }}/group_vars/all/etcd.yaml"

- name: Generate Kubespray addons.yaml
  vars:
    addons: "{{ config.addons.kubespray | default(none) }}"
  template:
    src: addons.yaml.j2
    dest: "{{ config_dir }}/group_vars/k8s_cluster/addons.yaml"