name: documentation
on:
  push:
    branches:
      - "release-*"
      #- master
  release:
    types:
      - published

env:
  PYTHON_VERSION: 3.x

jobs:

  # Documentation is deployed only on the latest release branch or on the new latest
  # release tag. This prevents bug fixes in older releases from overwriting the latest
  # documentation.
  check:
    name: Check if docs should be deployed
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.verify.outputs.deploy }}
    steps:
      - name: Extract release version from the branch name (or tag)
        id: branch_version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const branchName = process.env.GITHUB_REF_NAME
            const prefix = 'v'
            const releaseVersion = branchName.substring(branchName.lastIndexOf('-') + 1, branchName.length)
            return releaseVersion.startsWith(prefix) ? releaseVersion : prefix + releaseVersion

      - name: Get latest repository version
        id: latest_release_version
        uses: oprypin/find-latest-tag@v1.1.0
        with:
          repository: ${{ github.repository }}
          prefix: 'v'

      - name: Verify if the latest version contains current branch/tag version
        id: verify
        env:
          LATEST_VERSION: ${{ steps.latest_release_version.outputs.tag }}
          BRANCH_VERSION: ${{ steps.branch_version.outputs.result }}
        run: |
          echo "::set-output name=deploy::${{ contains(env.LATEST_VERSION, env.BRANCH_VERSION) }}"

  documentation:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.deploy == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python runtime
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          pip install \
            jinja2>=3.1 \
            markdown>=3.3 \
            mkdocs>=1.3 \
            mkdocs-material>=8.3.7 \
            mkdocs-material-extensions>=1.0.3 \
            mkdocs-minify-plugin>=0.5 \
            mkdocs-redirects>=1.0 \
            pygments>=2.12 \
            pymdown-extensions>=9.5

      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
